fixtures:
  repositories:
    "stdlib": "git://github.com/puppetlabs/puppetlabs-stdlib.git"
    "concat": "git://github.com/puppetlabs/puppetlabs-concat.git"
    "vcsrepo": "git://github.com/puppetlabs/puppetlabs-vcsrepo.git"
    "puppi": "git://github.com/example42/puppi.git"
  symlinks:
    "tp": "#{source_dir}"

