language: ruby
rvm:
  - 1.9.3
script:
  - "rake spec SPEC_OPTS='--format documentation'"
env:
  - PUPPET_VERSION="~> 2.6.18"
  - PUPPET_VERSION="~> 2.7.26"
  - PUPPET_VERSION="~> 3.7.3"
matrix:
  exclude:
    - rvm: 1.9.3
      env: PUPPET_VERSION="~> 2.6.18"
notifications:
  email:
    - al@lab42.it
